import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import prisma from '@/lib/db/prisma';
import storage from '@/lib/storage';
import * as guards from '@/lib/auth/guards';
import {
  VoiceboxProvider,
  VoiceProviderError,
  validateVoiceConsent,
  PRESET_VOICES,
  isPresetVoice,
  setVoiceProvider,
} from '@/lib/ai/voice-provider';
import {
  recordVoiceConsent,
  revokeVoiceConsent,
  getVoiceConsent,
} from '@/lib/persona/voice-consent';
import { POST as voicePost, GET as voiceGet } from '@/app/api/persona/voice/route';
import {
  POST as consentPost,
  GET as consentGet,
  DELETE as consentDelete,
} from '@/app/api/persona/voice/consent/route';

describe('Phase 5: Voice Provider and Consent Governance', () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    process.env = { ...originalEnv };
    vi.restoreAllMocks();
    setVoiceProvider(null);

    vi.spyOn(guards, 'requireAuth').mockResolvedValue({
      userId: 'test-user-1',
      email: 'owner@personaq.test',
      role: 'owner',
      twoFactorAuthenticated: true,
    });
    vi.spyOn(guards, 'requirePermission').mockResolvedValue({
      userId: 'test-user-1',
      email: 'owner@personaq.test',
      role: 'owner',
      twoFactorAuthenticated: true,
    });
  });

  afterEach(() => {
    process.env = { ...originalEnv };
    vi.restoreAllMocks();
    setVoiceProvider(null);
  });

  async function createTestPersona(data: Partial<Parameters<typeof prisma.persona.create>[0]['data']> = {}) {
    return prisma.persona.create({
      data: {
        name: 'Voice Test Persona',
        adultAge: 25,
        backstory: 'Voice test backstory',
        appearanceNotes: 'Natural appearance',
        voiceTone: 'Warm conversational',
        aiDisclosureText: 'AI Persona generated by PersonaQ',
        faceStatus: 'locked',
        ...data,
      },
    });
  }

  // =========================================================================
  // 1. Feature Flag Guard (FEATURE_VOICE=1)
  // =========================================================================
  describe('1. Feature Flag Guard (FEATURE_VOICE=1)', () => {
    it('blocks synthesis when FEATURE_VOICE is not 1', async () => {
      delete process.env.FEATURE_VOICE;

      const provider = new VoiceboxProvider();
      await expect(
        provider.synthesize({
          text: 'Hello, this is a test script.',
          voiceId: PRESET_VOICES[0].id,
        })
      ).rejects.toThrowError(VoiceProviderError);

      try {
        await provider.synthesize({
          text: 'Hello, this is a test script.',
          voiceId: PRESET_VOICES[0].id,
        });
      } catch (err: unknown) {
        expect(err).toBeInstanceOf(VoiceProviderError);
        expect((err as VoiceProviderError).code).toBe('feature_disabled');
      }
    });

    it('rejects POST /api/persona/voice with 403 when FEATURE_VOICE is not enabled', async () => {
      delete process.env.FEATURE_VOICE;

      const persona = await createTestPersona();

      try {
        const req = new Request('http://localhost:3000/api/persona/voice', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            text: 'Testing disabled voice',
            voiceId: PRESET_VOICES[0].id,
          }),
        });

        const res = await voicePost(req);
        expect(res.status).toBe(403);
        const data = await res.json();
        expect(data.code).toBe('FEATURE_DISABLED');
      } finally {
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });
  });

  // =========================================================================
  // 2. Preset Voices vs Custom Voices & Consent Validation
  // =========================================================================
  describe('2. Preset Voices vs Custom Voices & Consent Validation', () => {
    it('identifies system preset voices correctly', () => {
      for (const preset of PRESET_VOICES) {
        expect(isPresetVoice(preset.id)).toBe(true);
      }
      expect(isPresetVoice('unauthorized_voice_clone')).toBe(false);
    });

    it('allows preset voices without requiring custom consent', async () => {
      const validation = await validateVoiceConsent(PRESET_VOICES[0].id);
      expect(validation.allowed).toBe(true);
      expect(validation.isPreset).toBe(true);
      expect(validation.reason).toContain('Preset voice authorized');
    });

    it('strictly blocks custom voice synthesis when consent record is missing', async () => {
      const validation = await validateVoiceConsent('unauthorized_custom_voice_99');
      expect(validation.allowed).toBe(false);
      expect(validation.isPreset).toBe(false);
      expect(validation.reason).toContain('No recorded consent found');
      expect(validation.reason).toContain('Cloning of third-party voices is strictly prohibited');
    });

    it('allows custom voice when valid consent record exists', async () => {
      const voiceId = 'test_custom_voice_authorized_1';
      await recordVoiceConsent({
        voiceId,
        who: 'Jane Doe',
        scope: 'PersonaQ AI voice synthesis for testing',
        notes: 'Signed test release agreement',
      });

      try {
        const directConsent = await getVoiceConsent(voiceId);
        expect(directConsent?.who).toBe('Jane Doe');
        expect(directConsent?.scope).toContain('PersonaQ AI voice synthesis');

        const validation = await validateVoiceConsent(voiceId);
        expect(validation.allowed).toBe(true);
        expect(validation.isPreset).toBe(false);
        expect(validation.consent?.who).toBe('Jane Doe');
        expect(validation.consent?.scope).toContain('PersonaQ AI voice synthesis');
      } finally {
        await prisma.voiceConsent.deleteMany({ where: { voiceId } });
      }
    });

    it('blocks custom voice when consent record has been revoked', async () => {
      const voiceId = 'test_custom_voice_revoked_1';
      await recordVoiceConsent({
        voiceId,
        who: 'John Smith',
        scope: 'PersonaQ AI voice synthesis',
      });

      // Revoke consent
      await revokeVoiceConsent(voiceId);

      try {
        const validation = await validateVoiceConsent(voiceId);
        expect(validation.allowed).toBe(false);
        expect(validation.reason).toContain('was revoked');
      } finally {
        await prisma.voiceConsent.deleteMany({ where: { voiceId } });
      }
    });
  });

  // =========================================================================
  // 3. Voicebox Provider REST API & Cloning Prohibition
  // =========================================================================
  describe('3. Voicebox Provider & Third-Party Cloning Prohibition', () => {
    it('strictly rejects any third-party cloning attempt', async () => {
      process.env.FEATURE_VOICE = '1';
      const provider = new VoiceboxProvider();

      await expect(
        provider.synthesize({
          text: 'Attempting voice clone',
          voiceId: 'celebrity_clone_attempt',
          attemptCloning: true,
        })
      ).rejects.toMatchObject({
        code: 'voice_not_allowed',
      });
    });

    it('synthesizes audio via Voicebox REST API (127.0.0.1:17493)', async () => {
      process.env.FEATURE_VOICE = '1';
      const provider = new VoiceboxProvider('http://127.0.0.1:17493');

      // Mock fetch responding from Voicebox local REST API
      const fakeAudioBuffer = Buffer.from('RIFF....WAVEfmt ....data....');
      const fetchSpy = vi.spyOn(globalThis, 'fetch').mockImplementation(async (input, init) => {
        const urlStr = String(input);
        if (urlStr.includes('/health')) {
          return new Response(JSON.stringify({ status: 'ok' }), { status: 200 });
        }
        if (urlStr.includes('/v1/synthesize')) {
          const body = JSON.parse((init?.body as string) || '{}');
          expect(body.text).toBe('Welcome to PersonaQ audio studio.');
          expect(body.voice_id).toBe(PRESET_VOICES[0].id);

          return new Response(fakeAudioBuffer, {
            status: 200,
            headers: { 'Content-Type': 'audio/wav' },
          });
        }
        return new Response('Not found', { status: 404 });
      });

      const isAvailable = await provider.isAvailable();
      expect(isAvailable).toBe(true);

      const result = await provider.synthesize({
        text: 'Welcome to PersonaQ audio studio.',
        voiceId: PRESET_VOICES[0].id,
      });

      expect(result.buffer).toBeInstanceOf(Buffer);
      expect(result.mimeType).toBe('audio/wav');
      expect(result.voiceId).toBe(PRESET_VOICES[0].id);
      expect(result.isPreset).toBe(true);
      expect(result.aiGenerated).toBe(true);
      expect(fetchSpy).toHaveBeenCalled();
    });

    it('fails closed when Voicebox service is offline/unreachable', async () => {
      process.env.FEATURE_VOICE = '1';
      const provider = new VoiceboxProvider('http://127.0.0.1:17493');

      vi.spyOn(globalThis, 'fetch').mockRejectedValue(new Error('Connection refused'));

      await expect(
        provider.synthesize({
          text: 'Failing synthesis',
          voiceId: PRESET_VOICES[0].id,
        })
      ).rejects.toMatchObject({
        code: 'not_configured',
      });
    });
  });

  // =========================================================================
  // 4. API Endpoints & Mandatory AI Disclosure Asset Tagging
  // =========================================================================
  describe('4. API Routes & AI Disclosure Provenance Tagging', () => {
    it('POST /api/persona/voice creates audio asset with aiGenerated=true and full provenance', async () => {
      process.env.FEATURE_VOICE = '1';

      const persona = await createTestPersona();

      // Create face asset to satisfy locked-face rule
      const faceAsset = await prisma.asset.create({
        data: {
          personaId: persona.id,
          storageKey: `personas/${persona.id}/face.jpg`,
          type: 'image',
          kind: 'face_locked',
          aiGenerated: true,
          safetyStatus: 'passed',
        },
      });

      await prisma.persona.update({
        where: { id: persona.id },
        data: { faceAssetId: faceAsset.id },
      });

      // Mock storage and Voicebox REST API
      const fakeAudioBuffer = Buffer.from('RIFF1234WAVEfmt ');
      vi.spyOn(globalThis, 'fetch').mockResolvedValue(
        new Response(fakeAudioBuffer, {
          status: 200,
          headers: { 'Content-Type': 'audio/wav' },
        })
      );
      vi.spyOn(storage, 'upload').mockResolvedValue({
        url: `/uploads/personas/${persona.id}/audio_mock.wav`,
        storageKey: `personas/${persona.id}/audio_mock.wav`,
        bytes: fakeAudioBuffer.length,
      });

      try {
        const req = new Request('http://localhost:3000/api/persona/voice', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            text: 'Hello world, this is our official AI voice.',
            voiceId: PRESET_VOICES[0].id,
            speed: 1.1,
          }),
        });

        const res = await voicePost(req);
        expect(res.status).toBe(200);
        const data = await res.json();

        expect(data.success).toBe(true);
        expect(data.isPreset).toBe(true);
        expect(data.asset).toBeDefined();

        // Verify database persistence
        const dbAsset = await prisma.asset.findUnique({
          where: { id: data.asset.id },
        });

        expect(dbAsset).not.toBeNull();
        expect(dbAsset?.type).toBe('audio');
        expect(dbAsset?.aiGenerated).toBe(true); // Mandatory AI disclosure tag
        expect(dbAsset?.safetyStatus).toBe('passed');
        expect(dbAsset?.parentAssetId).toBe(faceAsset.id);

        const provenance = JSON.parse(dbAsset!.provenanceMeta!);
        expect(provenance.aiGenerated).toBe(true);
        expect(provenance.voiceId).toBe(PRESET_VOICES[0].id);
        expect(provenance.disclosureText).toBe(persona.aiDisclosureText);
        expect(provenance.speed).toBe(1.1);

        // Verify GET /api/persona/voice includes the generated audio asset
        const getReq = new Request(`http://localhost:3000/api/persona/voice?personaId=${persona.id}`);
        const getRes = await voiceGet(getReq);
        expect(getRes.status).toBe(200);
        const getData = await getRes.json();
        expect(getData.enabled).toBe(true);
        expect(getData.assets.length).toBeGreaterThanOrEqual(1);
        expect(getData.assets[0].type).toBe('audio');
      } finally {
        await prisma.asset.deleteMany({ where: { personaId: persona.id } });
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });

    it('POST /api/persona/voice rejects unlocked face with 409 Conflict', async () => {
      process.env.FEATURE_VOICE = '1';

      const persona = await createTestPersona({
        faceStatus: 'none',
        faceAssetId: null,
      });

      try {
        const req = new Request('http://localhost:3000/api/persona/voice', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            text: 'Trying voice on unlocked persona',
            voiceId: PRESET_VOICES[0].id,
          }),
        });

        const res = await voicePost(req);
        expect(res.status).toBe(409);
        const data = await res.json();
        expect(data.code).toBe('FACE_NOT_LOCKED');
      } finally {
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });

    it('rejects POST /api/persona/voice when custom voice lacks consent with 403 CONSENT_REQUIRED', async () => {
      process.env.FEATURE_VOICE = '1';

      const persona = await createTestPersona();
      const faceAsset = await prisma.asset.create({
        data: {
          personaId: persona.id,
          storageKey: `personas/${persona.id}/face.jpg`,
          type: 'image',
          kind: 'face_locked',
          aiGenerated: true,
          safetyStatus: 'passed',
        },
      });

      await prisma.persona.update({
        where: { id: persona.id },
        data: { faceAssetId: faceAsset.id },
      });

      try {
        const req = new Request('http://localhost:3000/api/persona/voice', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            text: 'Attempting custom voice without consent record',
            voiceId: 'unconsented_voice_xyz',
          }),
        });

        const res = await voicePost(req);
        expect(res.status).toBe(403);
        const data = await res.json();
        expect(data.code).toBe('CONSENT_REQUIRED');
        expect(data.error).toContain('strictly prohibited');
      } finally {
        await prisma.asset.deleteMany({ where: { personaId: persona.id } });
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });
  });

  // =========================================================================
  // 5. Consent Management API Endpoints
  // =========================================================================
  describe('5. Voice Consent Management CRUD API', () => {
    it('records, queries, and revokes consent via /api/persona/voice/consent', async () => {
      process.env.FEATURE_VOICE = '1';

      const testVoiceId = 'custom_voice_actor_bob_v1';

      try {
        // 1. Record Consent via POST
        const postReq = new Request('http://localhost:3000/api/persona/voice/consent', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            voiceId: testVoiceId,
            who: 'Bob Vance',
            scope: 'PersonaQ AI voice synthesis for marketing videos only',
            notes: 'Contract reference #BV-2026-99',
          }),
        });

        const postRes = await consentPost(postReq);
        expect(postRes.status).toBe(201);
        const postData = await postRes.json();
        expect(postData.consent.voiceId).toBe(testVoiceId);
        expect(postData.consent.who).toBe('Bob Vance');

        // 2. Query Consent via GET
        const getReq = new Request(`http://localhost:3000/api/persona/voice/consent?voiceId=${testVoiceId}`);
        const getRes = await consentGet(getReq);
        expect(getRes.status).toBe(200);
        const getData = await getRes.json();
        expect(getData.consent.voiceId).toBe(testVoiceId);
        expect(getData.consent.revokedAt).toBeNull();

        // 3. Revoke Consent via DELETE
        const deleteReq = new Request('http://localhost:3000/api/persona/voice/consent', {
          method: 'DELETE',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            voiceId: testVoiceId,
          }),
        });

        const deleteRes = await consentDelete(deleteReq);
        expect(deleteRes.status).toBe(200);
        const deleteData = await deleteRes.json();
        expect(deleteData.consent.revokedAt).not.toBeNull();

        // 4. Verify consent lookup now marks it revoked
        const getRevokedReq = new Request(`http://localhost:3000/api/persona/voice/consent?voiceId=${testVoiceId}`);
        const getRevokedRes = await consentGet(getRevokedReq);
        const revokedData = await getRevokedRes.json();
        expect(revokedData.consent.revokedAt).not.toBeNull();
      } finally {
        await prisma.voiceConsent.deleteMany({ where: { voiceId: testVoiceId } });
      }
    });
  });
});
