import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import prisma from '@/lib/db/prisma';
import storage from '@/lib/storage';
import * as guards from '@/lib/auth/guards';
import sharp from 'sharp';
import {
  buildShotPrompt,
  buildVideoPromptForAsset,
  parseLightingRecipe,
  formatLightingRecipe,
} from '@/lib/persona/shot-prompt';
import { CANONICAL_SHOT_TEMPLATES, seedShotTemplates } from '@/lib/persona/shot-templates';
import { setConsistencyEvaluator } from '@/lib/persona/consistency';
import { POST as shotLadderPost, GET as shotLadderGet } from '@/app/api/persona/shot-ladder/route';
import { POST as sceneSetsPost, GET as sceneSetsGet } from '@/app/api/persona/scene-sets/route';
import * as imageProviderModule from '@/lib/ai/image-provider';

describe('Phase 4: Scene Templates and Shot Ladder', () => {
  beforeEach(() => {
    vi.restoreAllMocks();
    vi.spyOn(guards, 'requireAuth').mockResolvedValue({
      userId: 'test-user-1',
      email: 'owner@personaq.test',
      role: 'owner',
      twoFactorAuthenticated: true,
    });
    vi.spyOn(guards, 'requirePermission').mockResolvedValue({
      userId: 'test-user-1',
      email: 'owner@personaq.test',
      role: 'owner',
      twoFactorAuthenticated: true,
    });

    setConsistencyEvaluator(async () => ({
      score: 88,
      passed: true,
      status: 'consistent',
      reasons: ['Consistent bone structure', 'Matching eye colour and features'],
    }));
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  async function createTestImageBuffer(width = 200, height = 200): Promise<Buffer> {
    return sharp({
      create: {
        width,
        height,
        channels: 3,
        background: { r: 230, g: 215, b: 195 },
      },
    })
      .jpeg()
      .toBuffer();
  }

  async function createTestPersona(data: Partial<Parameters<typeof prisma.persona.create>[0]['data']> = {}) {
    return prisma.persona.create({
      data: {
        name: 'Test Persona',
        adultAge: 25,
        backstory: 'Default test backstory for persona',
        appearanceNotes: 'Natural healthy features, expressive eyes.',
        voiceTone: 'Calm, articulate',
        aiDisclosureText: 'AI Persona generated by PersonaQ',
        faceStatus: 'none',
        ...data,
      },
    });
  }

  // =========================================================================
  // 1. Prompt Order and Verbatim Text (never paraphrased)
  // =========================================================================
  describe('1. Prompt Builder & Order Verification', () => {
    it('composes prompt in strict fixed order with unparaphrased identity and set text', () => {
      const verbatimIdentity = 'Exact identity text: Mediterranean skin tone, dark wavy hair, sharp jawline, hazel eyes.';
      const verbatimSet = 'Exact set text: Industrial loft living room, exposed red brick wall, warm timber floor, steel frame window.';

      const template = CANONICAL_SHOT_TEMPLATES[0]; // portrait 50mm T2
      const result = buildShotPrompt({
        persona: {
          name: 'Elena Rostova',
          identityText: verbatimIdentity,
          appearanceNotes: 'Fall-back appearance',
          adultAge: 27,
        },
        sceneSet: {
          name: 'Industrial Loft',
          setText: verbatimSet,
          lightingJson: JSON.stringify({
            keyDirection: '45-degree key light from camera left',
            timeOfDay: 'golden hour soft natural ambient',
            volumetric: 'subtle dust motes in sunbeam',
            rimLight: 'gentle edge rim lighting outlining shoulders',
            bokeh: 'natural circular optical bokeh in background',
            colourGrade: 'cinematic neutral warm grade',
          }),
        },
        template,
        expression: 'slight natural smile',
        action: 'resting elbow on walnut desk',
      });

      // 1. Verbatim check: identity and set text MUST exist unmodified
      expect(result.prompt).toContain(verbatimIdentity);
      expect(result.prompt).toContain(verbatimSet);
      expect(result.identityTextVerbatim).toBe(verbatimIdentity);
      expect(result.setTextVerbatim).toBe(verbatimSet);

      // 2. Strict order check
      const idxIdentity = result.prompt.indexOf(verbatimIdentity);
      const idxAction = result.prompt.indexOf('Action: resting elbow on walnut desk');
      const idxSet = result.prompt.indexOf(verbatimSet);
      const idxLighting = result.prompt.indexOf('Lighting Recipe:');
      const idxCamera = result.prompt.indexOf('Camera & Optics:');
      const idxAspect = result.prompt.indexOf('Aspect Ratio:');
      const idxNegative = result.prompt.indexOf('Negative Constraints:');

      expect(idxIdentity).toBeGreaterThanOrEqual(0);
      expect(idxAction).toBeGreaterThan(idxIdentity);
      expect(idxSet).toBeGreaterThan(idxAction);
      expect(idxLighting).toBeGreaterThan(idxSet);
      expect(idxCamera).toBeGreaterThan(idxLighting);
      expect(idxAspect).toBeGreaterThan(idxCamera);
      expect(idxNegative).toBeGreaterThan(idxAspect);

      // 3. Negative text and logo exclusion check
      expect(result.negativePrompt).toContain('no text, no logos, no stickers');
      expect(result.negativePrompt).toContain('brand logo');
      expect(result.negativePrompt).toContain('trademark');
      expect(result.negativePrompt).toContain('minor');
      expect(result.prompt).not.toMatch(/Apple|Nike|Sony|Canon|Starbucks|Gucci|Chanel/i);
    });

    it('falls back gracefully to appearanceNotes when identityText is not provided', () => {
      const verbatimAppearance = 'Verbatim fallback notes: olive skin, athletic build, short dark brown hair.';
      const template = CANONICAL_SHOT_TEMPLATES[1]; // wide 35mm T2.8

      const result = buildShotPrompt({
        persona: {
          name: 'Marco Silva',
          appearanceNotes: verbatimAppearance,
          adultAge: 30,
        },
        sceneSet: {
          name: 'Coastal Cliff',
          setText: 'Verbatim cliffs overlooking deep blue Mediterranean sea.',
          lightingJson: {},
        },
        template,
      });

      expect(result.prompt).toContain(verbatimAppearance);
      expect(result.identityTextVerbatim).toBe(verbatimAppearance);
    });

    it('correctly parses and formats lighting recipes', () => {
      const parsed = parseLightingRecipe(
        JSON.stringify({
          keyDirection: 'top down diffused softbox',
          rimLight: 'blue neon rim',
        })
      );
      expect(parsed.keyDirection).toBe('top down diffused softbox');
      expect(parsed.rimLight).toBe('blue neon rim');

      const formatted = formatLightingRecipe(parsed);
      expect(formatted).toContain('Key direction: top down diffused softbox');
      expect(formatted).toContain('Rim light: blue neon rim');
    });
  });

  // =========================================================================
  // 2. Video Prompt Generation (single camera move, subject still, timed beats)
  // =========================================================================
  describe('2. Video Prompt & Beats Specification', () => {
    it('builds single camera move prompt where subject stays still for portrait', () => {
      const result = buildVideoPromptForAsset(CANONICAL_SHOT_TEMPLATES[0]); // portrait

      expect(result.videoPrompt).toContain('Single continuous camera move');
      expect(result.videoPrompt).toContain('subject maintains still posture');
      expect(result.beats.length).toBeGreaterThanOrEqual(2);
      expect(result.beats[0].startSec).toBe(0);
      expect(result.beats[result.beats.length - 1].endSec).toBeGreaterThan(0);
    });

    it('builds single camera move for action and full_body rungs', () => {
      const actionResult = buildVideoPromptForAsset(CANONICAL_SHOT_TEMPLATES[1], 'holding coffee mug');
      expect(actionResult.videoPrompt).toContain('Single continuous camera move');
      expect(actionResult.videoPrompt).toContain('dolly');
      expect(actionResult.beats[0].action).toContain('coffee mug');

      const fullBodyResult = buildVideoPromptForAsset(
        { name: 'Full Body Standing', kind: 'full_body', cameraState: 'tripod locked' }
      );
      expect(fullBodyResult.videoPrompt).toContain('Single continuous camera move');
      expect(fullBodyResult.videoPrompt).toContain('pedestal');
    });
  });

  // =========================================================================
  // 3. Locked-Face Gate (409 Conflict if not locked)
  // =========================================================================
  describe('3. Shot Ladder 409 Lock Gate', () => {
    it('returns 409 Conflict when persona face is unlocked or faceAssetId is missing', async () => {
      const persona = await createTestPersona({
        name: 'Unlocked Test Persona',
        adultAge: 25,
        appearanceNotes: 'Dark eyes, light brown hair',
        faceStatus: 'none',
      });

      const sceneSet = await prisma.sceneSet.create({
        data: {
          personaId: persona.id,
          name: 'Studio White',
          setText: 'Clean white studio backdrop with soft shadows.',
          lightingJson: JSON.stringify({ keyDirection: 'frontal softbox' }),
        },
      });

      try {
        const req = new Request('http://localhost:3000/api/persona/shot-ladder', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            sceneSetId: sceneSet.id,
          }),
        });

        const res = await shotLadderPost(req);
        expect(res.status).toBe(409);
        const data = await res.json();
        expect(data.code).toBe('FACE_NOT_LOCKED');
        expect(data.error).toContain('must be locked');
      } finally {
        await prisma.sceneSet.deleteMany({ where: { personaId: persona.id } });
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });

    it('returns 404 when scene set does not belong to persona', async () => {
      const persona = await createTestPersona({
        name: 'Other Persona',
        adultAge: 26,
        appearanceNotes: 'Test appearance',
        faceStatus: 'locked',
        faceAssetId: 'dummy-face-id',
      });

      try {
        const req = new Request('http://localhost:3000/api/persona/shot-ladder', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            sceneSetId: 'non-existent-set-id',
          }),
        });

        const res = await shotLadderPost(req);
        expect(res.status).toBe(404);
        const data = await res.json();
        expect(data.code).toBe('SCENE_SET_NOT_FOUND');
      } finally {
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });
  });

  // =========================================================================
  // 4. Reference Capping at 3 and Ladder Execution (Portrait -> Action -> Full-Body)
  // =========================================================================
  describe('4. Reference Capping and Ladder Persistence', () => {
    it('executes shot ladder with references capped at 3 and persists videoPrompt + beatsJson', async () => {
      await seedShotTemplates(prisma);

      const persona = await createTestPersona({
        name: 'Locked Test Persona',
        adultAge: 28,
        identityText: 'Identity: High cheekbones, warm amber eyes, dark textured curls.',
        appearanceNotes: 'Natural warm glow, elegant posture.',
        faceStatus: 'locked',
      });

      // Create test face asset
      const testBuffer = await createTestImageBuffer(150, 150);
      const faceUpload = await storage.upload(testBuffer, `personas/${persona.id}/locked_face.jpg`, 'image/jpeg');

      const faceAsset = await prisma.asset.create({
        data: {
          personaId: persona.id,
          storageKey: `personas/${persona.id}/locked_face.jpg`,
          url: faceUpload.url,
          type: 'image',
          kind: 'face_primary',
          suitability: 'sfw_safe',
          aiGenerated: true,
          safetyStatus: 'passed',
        },
      });

      await prisma.persona.update({
        where: { id: persona.id },
        data: { faceAssetId: faceAsset.id },
      });

      const sceneSet = await prisma.sceneSet.create({
        data: {
          personaId: persona.id,
          name: 'Minimalist Penthouse',
          setText: 'Floor to ceiling windows overlooking twilight city skyline.',
          lightingJson: JSON.stringify({
            keyDirection: 'lateral warm lamp glow from left',
            timeOfDay: 'blue hour twilight exterior',
          }),
        },
      });

      // Mock ImageProvider to inspect options passed to it
      const capturedOpts: imageProviderModule.ImageGenerationOptions[] = [];
      const mockProvider: imageProviderModule.ImageProvider = {
        name: 'mock_ladder_provider',
        capabilities: { referenceImage: true },
        isAvailable: async () => true,
        generateImage: async (opts) => {
          capturedOpts.push(opts);
          const buf = await createTestImageBuffer(200, 200);
          return {
            buffer: buf,
            mimeType: 'image/jpeg',
            provider: 'mock_ladder_provider',
            model: 'mock-model-v1',
            estimatedCost: 0.04,
          };
        },
      };

      vi.spyOn(imageProviderModule, 'getImageProvider').mockReturnValue(mockProvider);

      try {
        const req = new Request('http://localhost:3000/api/persona/shot-ladder', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            sceneSetId: sceneSet.id,
            action: 'reading an architectural monograph',
            expression: 'focused curiosity',
          }),
        });

        const res = await shotLadderPost(req);
        expect(res.status).toBe(200);
        const data = await res.json();

        expect(data.success).toBe(true);
        expect(data.results).toHaveLength(3); // portrait, action, full_body

        // Verify the 3 rungs
        expect(data.results[0].step).toBe('portrait');
        expect(data.results[1].step).toBe('action');
        expect(data.results[2].step).toBe('full_body');

        // Check reference capping rule: references must NEVER exceed 3
        expect(capturedOpts).toHaveLength(3);
        for (const opts of capturedOpts) {
          expect(opts.referenceImages).toBeDefined();
          expect((opts.referenceImages || []).length).toBeLessThanOrEqual(3);
          expect(opts.referenceImages!.length).toBeGreaterThanOrEqual(1);

          // Prompt order checks on what was sent to provider
          expect(opts.prompt).toContain(persona.identityText!);
          expect(opts.prompt).toContain(sceneSet.setText);
          expect(opts.negativePrompt).toContain('no text, no logos, no stickers');
        }

        // Verify assets persisted in database with video metadata
        for (const rung of data.results) {
          const dbAsset = await prisma.asset.findUnique({
            where: { id: rung.asset.id },
          });

          expect(dbAsset).not.toBeNull();
          expect(dbAsset?.videoPrompt).toBeDefined();
          expect(dbAsset?.videoPrompt).toContain('Single continuous camera move');
          expect(dbAsset?.beatsJson).toBeDefined();

          const parsedBeats = JSON.parse(dbAsset!.beatsJson!);
          expect(Array.isArray(parsedBeats)).toBe(true);
          expect(parsedBeats.length).toBeGreaterThan(0);
          expect(parsedBeats[0]).toHaveProperty('startSec');
          expect(parsedBeats[0]).toHaveProperty('endSec');
          expect(parsedBeats[0]).toHaveProperty('action');
        }

        // Verify GET /api/persona/shot-ladder?personaId=...
        const getLadderReq = new Request(`http://localhost:3000/api/persona/shot-ladder?personaId=${persona.id}`);
        const getLadderRes = await shotLadderGet(getLadderReq);
        expect(getLadderRes.status).toBe(200);
        const getLadderData = await getLadderRes.json();
        expect(getLadderData.templates.length).toBeGreaterThanOrEqual(6);
        expect(getLadderData.assets.length).toBeGreaterThanOrEqual(3);
      } finally {
        await prisma.asset.deleteMany({ where: { personaId: persona.id } });
        await prisma.sceneSet.deleteMany({ where: { personaId: persona.id } });
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });
  });

  // =========================================================================
  // 5. Scene Sets CRUD Route
  // =========================================================================
  describe('5. Scene Sets API Endpoint', () => {
    it('creates and retrieves scene sets for a persona', async () => {
      const persona = await createTestPersona({
        name: 'Scene Set Persona',
        adultAge: 24,
        appearanceNotes: 'Classic looks',
      });

      try {
        // Create SceneSet via POST
        const postReq = new Request('http://localhost:3000/api/persona/scene-sets', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            personaId: persona.id,
            name: 'Sunlit Art Studio',
            setText: 'Spacious loft with high ceilings, white easel, oil paints on rustic wooden table, north-facing windows.',
            lightingJson: {
              keyDirection: 'soft diffuse north skylight',
              timeOfDay: 'midday overcast',
              bokeh: 'subtle out of focus canvas in background',
            },
          }),
        });

        const postRes = await sceneSetsPost(postReq);
        expect(postRes.status).toBe(201);
        const postData = await postRes.json();
        expect(postData.sceneSet.name).toBe('Sunlit Art Studio');
        expect(postData.sceneSet.setText).toContain('Spacious loft');

        // Fetch SceneSets via GET
        const getReq = new Request(`http://localhost:3000/api/persona/scene-sets?personaId=${persona.id}`);
        const getRes = await sceneSetsGet(getReq);
        expect(getRes.status).toBe(200);
        const getData = await getRes.json();
        expect(getData.sceneSets).toHaveLength(1);
        expect(getData.sceneSets[0].name).toBe('Sunlit Art Studio');
      } finally {
        await prisma.sceneSet.deleteMany({ where: { personaId: persona.id } });
        await prisma.persona.deleteMany({ where: { id: persona.id } });
      }
    });
  });
});
